"""init

Revision ID: c083553fda7a
Revises: 
Create Date: 2026-08-19 09:28:17.150292

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c083553fda7a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audience_phrase',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('exact_text', sa.String(), nullable=False),
    sa.Column('exact_context', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('normalized_concept', sa.String(), nullable=True),
    sa.Column('normalized_label', sa.String(), nullable=True),
    sa.Column('marketing_interpretation', sa.JSON(), nullable=True),
    sa.Column('occurrences', sa.Integer(), nullable=True),
    sa.Column('distinct_authors', sa.Integer(), nullable=True),
    sa.Column('variants', sa.JSON(), nullable=True),
    sa.Column('distinctiveness', sa.Float(), nullable=True),
    sa.Column('resonance_signal', sa.Float(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('detected_language', sa.String(), nullable=True),
    sa.Column('translated_interpretation', sa.JSON(), nullable=True),
    sa.Column('suppressed', sa.Boolean(), nullable=True),
    sa.Column('audience_id', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('supersedes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_by', sa.String(), nullable=True),
    sa.Column('review_notes', sa.String(), nullable=True),
    sa.Column('observed_fact', sa.String(), nullable=True),
    sa.Column('ai_interpretation', sa.String(), nullable=True),
    sa.Column('hypothesis', sa.String(), nullable=True),
    sa.Column('recommended_action', sa.String(), nullable=True),
    sa.Column('first_detected', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_detected', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('detected', 'analyzed', 'candidate', 'reviewed', 'trusted', 'archived', 'rejected')", name='ck_insight_status'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('audience_id', 'exact_text', 'category', name='uq_audience_phrase_text_cat')
    )
    op.create_index('ix_audience_phrase_concept', 'audience_phrase', ['normalized_concept'], unique=False)
    op.create_index('ix_audience_phrase_distinctiveness', 'audience_phrase', ['audience_id', 'distinctiveness'], unique=False)
    op.create_table('audit_log',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('author',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('author_hash', sa.String(), nullable=False),
    sa.Column('platform_author_id', sa.String(), nullable=True),
    sa.Column('display_handle', sa.String(), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('item_count', sa.Integer(), nullable=False),
    sa.Column('is_likely_bot', sa.Boolean(), nullable=False),
    sa.Column('is_creator', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('platform', 'author_hash', name='uq_author_platform_hash')
    )
    op.create_index('ix_author_hash', 'author', ['author_hash'], unique=False)
    op.create_table('competitor',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('priority', sa.String(), nullable=True),
    sa.Column('website', sa.String(), nullable=True),
    sa.Column('blog_feed', sa.String(), nullable=True),
    sa.Column('sitemap', sa.String(), nullable=True),
    sa.Column('youtube_channel', sa.String(), nullable=True),
    sa.Column('social_accounts', sa.JSON(), nullable=True),
    sa.Column('brand_terms', sa.JSON(), nullable=True),
    sa.Column('product', sa.JSON(), nullable=True),
    sa.Column('pricing', sa.JSON(), nullable=True),
    sa.Column('pricing_last_verified', sa.DateTime(timezone=True), nullable=True),
    sa.Column('monitor', sa.JSON(), nullable=True),
    sa.Column('data_quality', sa.String(), nullable=True),
    sa.Column('content_items_total', sa.Integer(), nullable=True),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('health', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('content',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('origin_type', sa.String(), nullable=False),
    sa.Column('origin_id', sa.String(), nullable=False),
    sa.Column('audience_id', sa.String(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('text_hash', sa.String(), nullable=False),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('source_id', sa.String(), nullable=False),
    sa.Column('author_hash', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('origin_type', 'origin_id', name='uq_content_origin')
    )
    op.create_index('ix_content_audience_posted', 'content', ['audience_id', 'posted_at'], unique=False)
    op.create_index('ix_content_author_hash', 'content', ['author_hash'], unique=False)
    op.create_index('ix_content_text_hash', 'content', ['text_hash'], unique=False)
    op.create_table('cost_ledger',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('agent', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('model_tier', sa.String(), nullable=False),
    sa.Column('tokens_in', sa.Integer(), nullable=False),
    sa.Column('tokens_out', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('content_id', sa.String(), nullable=True),
    sa.Column('cache_hit', sa.Boolean(), nullable=False),
    sa.Column('job_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cost_ledger_agent', 'cost_ledger', ['agent'], unique=False)
    op.create_index('ix_cost_ledger_occurred_at', 'cost_ledger', ['occurred_at'], unique=False)
    op.create_table('objection',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('objection', sa.String(), nullable=True),
    sa.Column('normalized_objection', sa.String(), nullable=True),
    sa.Column('objection_type', sa.String(), nullable=True),
    sa.Column('secondary_type', sa.String(), nullable=True),
    sa.Column('raised_at_stage', sa.String(), nullable=True),
    sa.Column('directed_at', sa.String(), nullable=True),
    sa.Column('stated_concern', sa.String(), nullable=True),
    sa.Column('likely_underlying_concern', sa.String(), nullable=True),
    sa.Column('underlying_confidence', sa.Float(), nullable=True),
    sa.Column('evidence_for_underlying', sa.JSON(), nullable=True),
    sa.Column('severity_to_conversion', sa.String(), nullable=True),
    sa.Column('possible_responses', sa.JSON(), nullable=True),
    sa.Column('responses_to_avoid', sa.JSON(), nullable=True),
    sa.Column('addressability', sa.Integer(), nullable=True),
    sa.Column('objection_priority', sa.Integer(), nullable=True),
    sa.Column('audience_id', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('supersedes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_by', sa.String(), nullable=True),
    sa.Column('review_notes', sa.String(), nullable=True),
    sa.Column('observed_fact', sa.String(), nullable=True),
    sa.Column('ai_interpretation', sa.String(), nullable=True),
    sa.Column('hypothesis', sa.String(), nullable=True),
    sa.Column('recommended_action', sa.String(), nullable=True),
    sa.Column('first_detected', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_detected', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('detected', 'analyzed', 'candidate', 'reviewed', 'trusted', 'archived', 'rejected')", name='ck_insight_status'),
    sa.CheckConstraint('underlying_confidence <= confidence', name='ck_objection_underlying_conf'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('opportunity',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('audience_id', sa.String(), nullable=False),
    sa.Column('opportunity_class', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('slug', sa.String(), nullable=True),
    sa.Column('core_idea', sa.String(), nullable=True),
    sa.Column('audience_segments', sa.JSON(), nullable=True),
    sa.Column('problem_ref', sa.String(), nullable=True),
    sa.Column('audience_language', sa.JSON(), nullable=True),
    sa.Column('scores', sa.JSON(), nullable=True),
    sa.Column('opportunity_score', sa.Integer(), nullable=True),
    sa.Column('score_band', sa.String(), nullable=True),
    sa.Column('recommended_platform', sa.JSON(), nullable=True),
    sa.Column('format', sa.JSON(), nullable=True),
    sa.Column('angle', sa.String(), nullable=True),
    sa.Column('hook_ideas', sa.JSON(), nullable=True),
    sa.Column('structure_suggestion', sa.JSON(), nullable=True),
    sa.Column('cta_idea', sa.String(), nullable=True),
    sa.Column('do_not_say', sa.JSON(), nullable=True),
    sa.Column('claims_requiring_verification', sa.JSON(), nullable=True),
    sa.Column('blocked', sa.Boolean(), nullable=True),
    sa.Column('decision', sa.String(), nullable=True),
    sa.Column('decision_reason', sa.String(), nullable=True),
    sa.Column('outcome', sa.JSON(), nullable=True),
    sa.Column('exported_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('export_schema_version', sa.String(), nullable=True),
    sa.Column('thresholds_met', sa.JSON(), nullable=True),
    sa.Column('gate_status', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_opportunity_audience_score', 'opportunity', ['audience_id', 'status', 'opportunity_score'], unique=False)
    op.create_index('ix_opportunity_decision', 'opportunity', ['decision'], unique=False)
    op.create_table('question',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('question', sa.String(), nullable=True),
    sa.Column('normalized_question', sa.String(), nullable=True),
    sa.Column('question_variants', sa.JSON(), nullable=True),
    sa.Column('intent', sa.String(), nullable=True),
    sa.Column('intent_confidence', sa.Float(), nullable=True),
    sa.Column('secondary_intent', sa.String(), nullable=True),
    sa.Column('urgency_score', sa.Integer(), nullable=True),
    sa.Column('answered_in_thread_rate', sa.Float(), nullable=True),
    sa.Column('content_potential', sa.Integer(), nullable=True),
    sa.Column('business_potential', sa.Integer(), nullable=True),
    sa.Column('platform_distribution', sa.JSON(), nullable=True),
    sa.Column('competitor_coverage', sa.JSON(), nullable=True),
    sa.Column('suggested_formats', sa.JSON(), nullable=True),
    sa.Column('hooks', sa.JSON(), nullable=True),
    sa.Column('asked_by', sa.String(), nullable=True),
    sa.Column('is_rhetorical', sa.Boolean(), nullable=True),
    sa.Column('audience_id', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('supersedes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_by', sa.String(), nullable=True),
    sa.Column('review_notes', sa.String(), nullable=True),
    sa.Column('observed_fact', sa.String(), nullable=True),
    sa.Column('ai_interpretation', sa.String(), nullable=True),
    sa.Column('hypothesis', sa.String(), nullable=True),
    sa.Column('recommended_action', sa.String(), nullable=True),
    sa.Column('first_detected', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_detected', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('detected', 'analyzed', 'candidate', 'reviewed', 'trusted', 'archived', 'rejected')", name='ck_insight_status'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('audience_id', 'slug', name='uq_question_slug')
    )
    op.create_index('ix_question_audience_status_urgency', 'question', ['audience_id', 'status', 'urgency_score'], unique=False)
    op.create_index('ix_question_intent', 'question', ['intent'], unique=False)
    op.create_table('quota_ledger',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('units_used', sa.Integer(), nullable=False),
    sa.Column('units_limit', sa.Integer(), nullable=False),
    sa.Column('requests', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('platform', 'date', name='uq_quota_ledger_platform_date')
    )
    op.create_table('report',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('report_type', sa.String(), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.Column('word_count', sa.Integer(), nullable=True),
    sa.Column('insight_refs', sa.JSON(), nullable=True),
    sa.Column('validation_status', sa.String(), nullable=True),
    sa.Column('caveats', sa.JSON(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('review_action',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('insight_type', sa.String(), nullable=False),
    sa.Column('insight_id', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('from_status', sa.String(), nullable=True),
    sa.Column('to_status', sa.String(), nullable=True),
    sa.Column('reason_code', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('field_changes', sa.JSON(), nullable=True),
    sa.Column('actor', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_review_action_action', 'review_action', ['action', 'created_at'], unique=False)
    op.create_index('ix_review_action_insight', 'review_action', ['insight_type', 'insight_id', 'created_at'], unique=False)
    op.create_table('source',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('audience_id', sa.String(), nullable=False),
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('query', sa.String(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.String(), nullable=False),
    sa.Column('collection_frequency', sa.String(), nullable=False),
    sa.Column('config_json', sa.JSON(), nullable=False),
    sa.Column('config_hash', sa.String(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_cursor', sa.String(), nullable=True),
    sa.Column('consecutive_failures', sa.Integer(), nullable=False),
    sa.Column('health', sa.String(), nullable=False),
    sa.Column('items_collected_total', sa.Integer(), nullable=False),
    sa.Column('relevant_rate_30d', sa.Float(), nullable=True),
    sa.Column('trusted_insights_attributed', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_source_audience_id_enabled_frequency', 'source', ['audience_id', 'enabled', 'collection_frequency'], unique=False)
    op.create_index('ix_source_health', 'source', ['health'], unique=False)
    op.create_table('topic',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('cluster_id', sa.String(), nullable=True),
    sa.Column('centroid_embedding_id', sa.String(), nullable=True),
    sa.Column('cohesion', sa.Float(), nullable=True),
    sa.Column('item_count', sa.Integer(), nullable=True),
    sa.Column('distinct_authors', sa.Integer(), nullable=True),
    sa.Column('platforms', sa.JSON(), nullable=True),
    sa.Column('share_of_voice', sa.Float(), nullable=True),
    sa.Column('superseded_by', sa.String(), nullable=True),
    sa.Column('audience_id', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('supersedes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_by', sa.String(), nullable=True),
    sa.Column('review_notes', sa.String(), nullable=True),
    sa.Column('observed_fact', sa.String(), nullable=True),
    sa.Column('ai_interpretation', sa.String(), nullable=True),
    sa.Column('hypothesis', sa.String(), nullable=True),
    sa.Column('recommended_action', sa.String(), nullable=True),
    sa.Column('first_detected', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_detected', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('detected', 'analyzed', 'candidate', 'reviewed', 'trusted', 'archived', 'rejected')", name='ck_insight_status'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_topic_audience_status', 'topic', ['audience_id', 'status'], unique=False)
    op.create_index('ix_topic_cluster', 'topic', ['cluster_id'], unique=False)
    op.create_table('collection_job',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('source_id', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('trigger', sa.String(), nullable=False),
    sa.Column('cursor_before', sa.String(), nullable=True),
    sa.Column('cursor_after', sa.String(), nullable=True),
    sa.Column('items_fetched', sa.Integer(), nullable=False),
    sa.Column('items_new', sa.Integer(), nullable=False),
    sa.Column('items_duplicate', sa.Integer(), nullable=False),
    sa.Column('items_rejected', sa.Integer(), nullable=False),
    sa.Column('api_calls', sa.Integer(), nullable=False),
    sa.Column('quota_units_used', sa.Integer(), nullable=False),
    sa.Column('error_class', sa.String(), nullable=True),
    sa.Column('error_detail', sa.String(), nullable=True),
    sa.Column('window_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('window_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['source.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_collection_job_source_started', 'collection_job', ['source_id', 'started_at'], unique=False)
    op.create_index('ix_collection_job_status_started', 'collection_job', ['status', 'started_at'], unique=False)
    op.create_table('competitor_content',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('competitor_id', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('format', sa.String(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('summary', sa.String(), nullable=True),
    sa.Column('word_count', sa.Integer(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('engagement', sa.JSON(), nullable=True),
    sa.Column('engagement_percentile', sa.Integer(), nullable=True),
    sa.Column('topic_id', sa.String(), nullable=True),
    sa.Column('topic_confidence', sa.Float(), nullable=True),
    sa.Column('is_primary_topic', sa.Boolean(), nullable=True),
    sa.Column('promoted_offers', sa.JSON(), nullable=True),
    sa.Column('data_quality', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['competitor_id'], ['competitor.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['topic.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('competitor_id', 'url', name='uq_competitor_content_url')
    )
    op.create_index('ix_competitor_content_pub', 'competitor_content', ['competitor_id', 'published_at'], unique=False)
    op.create_index('ix_competitor_content_topic', 'competitor_content', ['topic_id'], unique=False)
    op.create_table('competitor_coverage',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('competitor_id', sa.String(), nullable=False),
    sa.Column('topic_id', sa.String(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('coverage_score', sa.Integer(), nullable=True),
    sa.Column('volume_component', sa.Float(), nullable=True),
    sa.Column('depth_component', sa.Float(), nullable=True),
    sa.Column('recency_component', sa.Float(), nullable=True),
    sa.Column('directness_component', sa.Float(), nullable=True),
    sa.Column('items_on_topic', sa.Integer(), nullable=True),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('performance_index', sa.Float(), nullable=True),
    sa.Column('low_sample', sa.Boolean(), nullable=True),
    sa.Column('data_quality', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['competitor_id'], ['competitor.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['topic.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('competitor_gap',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('gap_type', sa.String(), nullable=True),
    sa.Column('topic_id', sa.String(), nullable=True),
    sa.Column('demand_score', sa.Integer(), nullable=True),
    sa.Column('market_coverage', sa.Integer(), nullable=True),
    sa.Column('coverage_by_competitor', sa.JSON(), nullable=True),
    sa.Column('competitors_checked', sa.JSON(), nullable=True),
    sa.Column('competitors_uncheckable', sa.JSON(), nullable=True),
    sa.Column('items_examined', sa.Integer(), nullable=True),
    sa.Column('examination_window_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('examination_window_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('unanswered_questions', sa.JSON(), nullable=True),
    sa.Column('opportunity_score', sa.Integer(), nullable=True),
    sa.Column('score_components', sa.JSON(), nullable=True),
    sa.Column('confidence_caps_applied', sa.JSON(), nullable=True),
    sa.Column('claims_requiring_verification', sa.JSON(), nullable=True),
    sa.Column('addressed_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['topic.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('embedding',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('content_id', sa.String(), nullable=True),
    sa.Column('owner_type', sa.String(), nullable=False),
    sa.Column('owner_id', sa.String(), nullable=False),
    sa.Column('vector', sa.LargeBinary(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('dimensions', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['content.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_type', 'owner_id', 'model', name='uq_embedding_owner_model')
    )
    op.create_table('item_analysis',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('content_id', sa.String(), nullable=False),
    sa.Column('prompt_version', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('model_tier', sa.String(), nullable=False),
    sa.Column('relevance_score', sa.Integer(), nullable=False),
    sa.Column('relevance_stage', sa.String(), nullable=False),
    sa.Column('relevance_reason', sa.String(), nullable=True),
    sa.Column('is_relevant', sa.Boolean(), nullable=False),
    sa.Column('intent', sa.String(), nullable=True),
    sa.Column('intent_confidence', sa.Float(), nullable=True),
    sa.Column('segments', sa.JSON(), nullable=True),
    sa.Column('extracted', sa.JSON(), nullable=True),
    sa.Column('is_rhetorical', sa.Boolean(), nullable=False),
    sa.Column('is_creator_content', sa.Boolean(), nullable=False),
    sa.Column('is_spam', sa.Boolean(), nullable=False),
    sa.Column('tokens_in', sa.Integer(), nullable=False),
    sa.Column('tokens_out', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('analyzed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('error', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['content.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('content_id', 'prompt_version', name='uq_item_analysis_content_prompt')
    )
    op.create_index('ix_item_analysis_is_relevant_analyzed', 'item_analysis', ['is_relevant', 'analyzed_at'], unique=False)
    op.create_index('ix_item_analysis_relevance_score', 'item_analysis', ['relevance_score'], unique=False)
    op.create_table('pain_point',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('category', sa.JSON(), nullable=True),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('severity_score', sa.Integer(), nullable=True),
    sa.Column('frequency', sa.Integer(), nullable=True),
    sa.Column('frequency_distinct_authors', sa.Integer(), nullable=True),
    sa.Column('frequency_change', sa.Float(), nullable=True),
    sa.Column('trend', sa.String(), nullable=True),
    sa.Column('platform_spread', sa.Integer(), nullable=True),
    sa.Column('topic_id', sa.String(), nullable=True),
    sa.Column('cluster_id', sa.String(), nullable=True),
    sa.Column('affected_segments', sa.JSON(), nullable=True),
    sa.Column('representative_quotes', sa.JSON(), nullable=True),
    sa.Column('paraphrased_examples', sa.JSON(), nullable=True),
    sa.Column('related_pains', sa.JSON(), nullable=True),
    sa.Column('single_thread', sa.Boolean(), nullable=True),
    sa.Column('audience_id', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('supersedes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_by', sa.String(), nullable=True),
    sa.Column('review_notes', sa.String(), nullable=True),
    sa.Column('observed_fact', sa.String(), nullable=True),
    sa.Column('ai_interpretation', sa.String(), nullable=True),
    sa.Column('hypothesis', sa.String(), nullable=True),
    sa.Column('recommended_action', sa.String(), nullable=True),
    sa.Column('first_detected', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_detected', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('detected', 'analyzed', 'candidate', 'reviewed', 'trusted', 'archived', 'rejected')", name='ck_insight_status'),
    sa.ForeignKeyConstraint(['topic_id'], ['topic.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('audience_id', 'slug', name='uq_pain_point_slug')
    )
    op.create_index('ix_pain_point_audience_status_severity', 'pain_point', ['audience_id', 'status', 'severity_score'], unique=False)
    op.create_index('ix_pain_point_last_detected', 'pain_point', ['last_detected'], unique=False)
    op.create_index('ix_pain_point_topic', 'pain_point', ['topic_id'], unique=False)
    op.create_table('trend',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('topic_id', sa.String(), nullable=False),
    sa.Column('window_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('window_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('window_completeness', sa.Float(), nullable=True),
    sa.Column('current_frequency', sa.Integer(), nullable=True),
    sa.Column('previous_frequency', sa.Integer(), nullable=True),
    sa.Column('baseline_mean', sa.Float(), nullable=True),
    sa.Column('baseline_stdev', sa.Float(), nullable=True),
    sa.Column('growth_rate', sa.Float(), nullable=True),
    sa.Column('velocity', sa.Float(), nullable=True),
    sa.Column('acceleration', sa.Float(), nullable=True),
    sa.Column('z_score', sa.Float(), nullable=True),
    sa.Column('classification', sa.String(), nullable=True),
    sa.Column('trend_score', sa.Integer(), nullable=True),
    sa.Column('significance_score', sa.Integer(), nullable=True),
    sa.Column('guards_fired', sa.JSON(), nullable=True),
    sa.Column('author_concentration', sa.Float(), nullable=True),
    sa.Column('external_trigger', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['topic.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('topic_id', 'window_end', name='uq_trend_topic_window')
    )
    op.create_index('ix_trend_window_significance', 'trend', ['window_end', 'significance_score'], unique=False)
    op.create_table('raw_payload',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('collection_job_id', sa.String(), nullable=False),
    sa.Column('platform_item_id', sa.String(), nullable=False),
    sa.Column('payload_gz', sa.LargeBinary(), nullable=False),
    sa.Column('payload_hash', sa.String(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['collection_job_id'], ['collection_job.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('collection_job_id', 'platform_item_id', name='uq_raw_payload_job_item')
    )
    op.create_index('ix_raw_payload_expires_at', 'raw_payload', ['expires_at'], unique=False)
    op.create_table('conversation',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('audience_id', sa.String(), nullable=False),
    sa.Column('source_id', sa.String(), nullable=False),
    sa.Column('raw_payload_id', sa.String(), nullable=False),
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('platform_item_id', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('body', sa.String(), nullable=True),
    sa.Column('body_hash', sa.String(), nullable=False),
    sa.Column('simhash', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.String(), nullable=True),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('detected_language', sa.String(), nullable=True),
    sa.Column('engagement', sa.JSON(), nullable=True),
    sa.Column('comment_count', sa.Integer(), nullable=False),
    sa.Column('is_duplicate_of', sa.String(), nullable=True),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('content_type', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['author.id'], ),
    sa.ForeignKeyConstraint(['is_duplicate_of'], ['conversation.id'], ),
    sa.ForeignKeyConstraint(['raw_payload_id'], ['raw_payload.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['source.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'platform_item_id', name='uq_conversation_source_item')
    )
    op.create_index('ix_conversation_audience_posted', 'conversation', ['audience_id', 'posted_at'], unique=False)
    op.create_index('ix_conversation_body_hash', 'conversation', ['body_hash'], unique=False)
    op.create_index('ix_conversation_is_duplicate', 'conversation', ['is_duplicate_of'], unique=False)
    op.create_index('ix_conversation_simhash', 'conversation', ['simhash'], unique=False)
    op.create_table('comment',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('conversation_id', sa.String(), nullable=False),
    sa.Column('parent_comment_id', sa.String(), nullable=True),
    sa.Column('depth', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(), nullable=False),
    sa.Column('body_hash', sa.String(), nullable=False),
    sa.Column('simhash', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.String(), nullable=True),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('engagement', sa.JSON(), nullable=True),
    sa.Column('is_author_reply', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['author.id'], ),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversation.id'], ),
    sa.ForeignKeyConstraint(['parent_comment_id'], ['comment.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('conversation_id', 'id', name='uq_comment_conv_item')
    )
    op.create_index('ix_comment_conversation_posted', 'comment', ['conversation_id', 'posted_at'], unique=False)
    op.create_table('evidence',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('insight_type', sa.String(), nullable=False),
    sa.Column('insight_id', sa.String(), nullable=False),
    sa.Column('content_id', sa.String(), nullable=False),
    sa.Column('conversation_id', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('source_id', sa.String(), nullable=False),
    sa.Column('author_hash', sa.String(), nullable=True),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('exact_phrasing', sa.String(), nullable=True),
    sa.Column('contribution', sa.String(), nullable=False),
    sa.Column('relevance_score', sa.Integer(), nullable=False),
    sa.Column('evidence_expired', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('LENGTH(exact_phrasing) <= 120', name='ck_evidence_phrasing_len'),
    sa.ForeignKeyConstraint(['content_id'], ['content.id'], ),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversation.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('insight_type', 'insight_id', 'content_id', name='uq_evidence_insight_content')
    )
    op.create_index('ix_evidence_author_hash', 'evidence', ['author_hash'], unique=False)
    op.create_index('ix_evidence_content', 'evidence', ['content_id'], unique=False)
    op.create_index('ix_evidence_insight', 'evidence', ['insight_type', 'insight_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_evidence_insight', table_name='evidence')
    op.drop_index('ix_evidence_content', table_name='evidence')
    op.drop_index('ix_evidence_author_hash', table_name='evidence')
    op.drop_table('evidence')
    op.drop_index('ix_comment_conversation_posted', table_name='comment')
    op.drop_table('comment')
    op.drop_index('ix_conversation_simhash', table_name='conversation')
    op.drop_index('ix_conversation_is_duplicate', table_name='conversation')
    op.drop_index('ix_conversation_body_hash', table_name='conversation')
    op.drop_index('ix_conversation_audience_posted', table_name='conversation')
    op.drop_table('conversation')
    op.drop_index('ix_raw_payload_expires_at', table_name='raw_payload')
    op.drop_table('raw_payload')
    op.drop_index('ix_trend_window_significance', table_name='trend')
    op.drop_table('trend')
    op.drop_index('ix_pain_point_topic', table_name='pain_point')
    op.drop_index('ix_pain_point_last_detected', table_name='pain_point')
    op.drop_index('ix_pain_point_audience_status_severity', table_name='pain_point')
    op.drop_table('pain_point')
    op.drop_index('ix_item_analysis_relevance_score', table_name='item_analysis')
    op.drop_index('ix_item_analysis_is_relevant_analyzed', table_name='item_analysis')
    op.drop_table('item_analysis')
    op.drop_table('embedding')
    op.drop_table('competitor_gap')
    op.drop_table('competitor_coverage')
    op.drop_index('ix_competitor_content_topic', table_name='competitor_content')
    op.drop_index('ix_competitor_content_pub', table_name='competitor_content')
    op.drop_table('competitor_content')
    op.drop_index('ix_collection_job_status_started', table_name='collection_job')
    op.drop_index('ix_collection_job_source_started', table_name='collection_job')
    op.drop_table('collection_job')
    op.drop_index('ix_topic_cluster', table_name='topic')
    op.drop_index('ix_topic_audience_status', table_name='topic')
    op.drop_table('topic')
    op.drop_index('ix_source_health', table_name='source')
    op.drop_index('ix_source_audience_id_enabled_frequency', table_name='source')
    op.drop_table('source')
    op.drop_index('ix_review_action_insight', table_name='review_action')
    op.drop_index('ix_review_action_action', table_name='review_action')
    op.drop_table('review_action')
    op.drop_table('report')
    op.drop_table('quota_ledger')
    op.drop_index('ix_question_intent', table_name='question')
    op.drop_index('ix_question_audience_status_urgency', table_name='question')
    op.drop_table('question')
    op.drop_index('ix_opportunity_decision', table_name='opportunity')
    op.drop_index('ix_opportunity_audience_score', table_name='opportunity')
    op.drop_table('opportunity')
    op.drop_table('objection')
    op.drop_index('ix_cost_ledger_occurred_at', table_name='cost_ledger')
    op.drop_index('ix_cost_ledger_agent', table_name='cost_ledger')
    op.drop_table('cost_ledger')
    op.drop_index('ix_content_text_hash', table_name='content')
    op.drop_index('ix_content_author_hash', table_name='content')
    op.drop_index('ix_content_audience_posted', table_name='content')
    op.drop_table('content')
    op.drop_table('competitor')
    op.drop_index('ix_author_hash', table_name='author')
    op.drop_table('author')
    op.drop_table('audit_log')
    op.drop_index('ix_audience_phrase_distinctiveness', table_name='audience_phrase')
    op.drop_index('ix_audience_phrase_concept', table_name='audience_phrase')
    op.drop_table('audience_phrase')
    # ### end Alembic commands ###
